Create new functions to calculate the design based index and plot the index by year and year-strata
pfmc-assessments/nwfscSurvey pull request #134
Opened 2024-06-21 19:46 UTC by chantelwetzel-noaa

This pull requests include new functions for calculating the design based index (`get_design_based()`) and for plotting (`plot_index()`) with the following changes:

`get_design_based()`
- This function will replace the `Biomass.fn()` that remains available with only a soft deprecation warning encouraging users to switch to `get_design_based()`
- The statistical method for calculating the design based index is unchanged.
- The output of the function has been cleaned up returning a list with the design based index for each strata and by year (all stratas combined).  
- The column names in the data-frames in the list have been revised to match the column name structure used by the `indexwc` package.
- A csv file that is formatted for SS3 is still provided if a directory is provided.
- The output of this function is designed to be used with the new `plot_index()` function.

`plot_index()`
- This function will replace the `PlotBio.fn()` and the `PlotBioStrata.fn()` with soft deprecation warnings added to both of these functions.
- This new functions allows users to get either both plots for strata-specific or year design based index with one function call.  
- Switches plotting to use `ggplot2`

A test has been added for `get_design_based()` and the vignette has been updated.

A new function to check the number of observations within a strata has also been included.  The `check_strata()` function is designed to replace the `CheckStrata.fn` with a soft deprecation warning added to this existing function. However, the new `get_design_based()` function is robust to stratas with no data, so if this function is being used, confirming the number of 
positive tows by observation are less critical but can help users identify large areas with limited positive observations that would impact data expantions.

2024-06-26 15:48 UTC, brianlangseth-NOAA commented
I can start doing this tomorrow and friday. Am on leave for much of next week so may not finish until after I return depending on what I find.

2024-07-08 23:43 UTC, brianlangseth-NOAA requested changes
Sorry this has taken me so long to get through. Most of my edits deal with fixes when dir is something other than NULL. Overall Im a fan of what you've done here. I like the simplified output of `get_design_based()` and think its easier to follow. 

Thanks for giving the chance to review. Although I feel like it took me longer than it should, I understand the calculations a lot better.

2024-07-08 23:43 UTC, brianlangseth-NOAA commented on R/plot_index.R
> +#' intervals.
I notice the old plots had CI's. These are somewhat informative to see the relative contribution of the strata, though they dont convey the relative area of each and therefore its contributions. What was the reason to remove the CI's? Note that I dont have a strong opinion here, and am in favor of incremental changes that move us forward (so am fine with the CI's omissions). I believe these strata based figures weren't widely used anyway.

2024-07-08 23:43 UTC, brianlangseth-NOAA commented on R/plot_index.R
> +        height = height, width = width, units = "in", res = res
```suggestion
        height = height, width = width, units = "in", dpi = res
```

2024-07-08 23:43 UTC, brianlangseth-NOAA commented on R/plot_index.R
> +        height = height, width = width, units = "in", res = res
This is predicated on my version of ggplot2 (version 3.5.1) being the most up to date. It looks like it is based on the current github page of ggplot2. Without this fix I get the following error when I have a non-null entry for "dir"

`Error in f(...) : 
formal argument "res" matched by multiple actual arguments`

2024-07-08 23:43 UTC, brianlangseth-NOAA commented on R/plot_index.R
> +        height = height, width = width, units = "in", res = res
```suggestion
        height = height, width = width, units = "in", dpi = res
```

2024-07-09 14:29 UTC, chantelwetzel-noaa commented on R/check_strata.R
> +      x = out,
Thank you for catching this. Fixed in 40de1eac8a5c53167e380e941d464cd716012abb

2024-07-09 17:41 UTC, chantelwetzel-noaa commented on R/get_design_based.R
> +      se = log(cv^2 + 1)
I have removed these items (cv, se, and log_var) from the output since I agree that they are likely to be confusing.  Additionally, the uncertainty for a specific-year strata combination can be extremely large and unhelpful to the user.

2024-07-09 17:47 UTC, chantelwetzel-noaa commented on R/get_design_based.R
> +      mean_est = sum(est),
The documentation has been revised to be clearer: 1e04408df2def9a567b0ff5116c125abae3f0bad

2024-07-09 17:50 UTC, chantelwetzel-noaa commented on R/get_design_based.R
> +      se_log = se_log
fixed

2024-07-09 17:55 UTC, chantelwetzel-noaa commented on R/plot_index.R
> +#' intervals.
The new code uses the lower and upper estimates calculated as: exp((log(est) - qnorm(1 - (1 - CI) / 2) * se_log)).  This calculation can not be done unless one has multiple positive observations within each year-strata combination based on the new code.  Additionally, even if there are positive observations for all year-strata combinations the uncertainty is extremely large, rendering it practically unusable, given the limited data. Finally, eliminating the uncertainty calculations for the year-strata estimates makes the code more robust while still rendering the key information for the year-based design-based index.

2024-07-09 18:00 UTC, chantelwetzel-noaa commented on R/plot_index.R
> +        height = height, width = width, units = "in", res = res
Nice catch.  I have fixed it and revised the function input accordingly to be clearer to users: e6a7433ba469d9d7ec95d64ee800a41c3055b56c

2024-07-09 18:00 UTC, chantelwetzel-noaa commented on R/plot_index.R
> +        height = height, width = width, units = "in", res = res
Fixed

2024-07-09 18:01 UTC, chantelwetzel-noaa commented
Thank you for the thorough review.  I have fixed all the items that you noted and made some useful clarifications based on your feedback.

2024-07-09 18:02 UTC, merged